"""Static fingerprint signature tables for TechFingerprinter.

Pure data - no logic lives here. Extracted from titan/core/fingerprint.py
so the detection methods stay readable and the tables stay auditable.
"""

from __future__ import annotations

BODY_SIGNATURES: dict[str, str] = {
    "wordpress": "WordPress",
    "drupal": "Drupal",
    "joomla": "Joomla",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "codeigniter": "CodeIgniter",
    "yii": "Yii",
    "phalcon": "Phalcon",
    "zend": "Zend",
    "cakePHP": "CakePHP",
    "fuelphp": "FuelPHP",
    "kohana": "Kohana",
    "slim": "Slim",
    "silex": "Silex",
    "lumen": "Lumen",
    "spark": "Spark",
    "adonis": "Adonis",
    "hapi": "Hapi",
    "meteor": "Meteor",
    "express": "Express",
    "koa": "Koa",
    "next.js": "Next.js",
    "nuxt.js": "Nuxt.js",
    "svelte": "Svelte",
    "gatsby": "Gatsby",
    "hugo": "Hugo",
    "jekyll": "Jekyll",
    "hexo": "Hexo",
    "gridsome": "Gridsome",
    "eleventy": "Eleventy",
    "astro": "Astro",
    "rails": "Ruby on Rails",
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "spring": "Spring",
    "struts": "Struts",
    "play": "Play Framework",
    "asp.net": "ASP.NET",
    "php": "PHP",
    "node.js": "Node.js",
    "react": "React",
    "vue": "Vue",
    "angular": "Angular",
    "jquery": "jQuery",
    "bootstrap": "Bootstrap",
    "tailwind": "Tailwind",
    "foundation": "Foundation",
    "materialize": "Materialize",
    "bulma": "Bulma",
    "semantic-ui": "Semantic UI",
    "antd": "Ant Design",
    "element-ui": "Element UI",
    "vuetify": "Vuetify",
    "buefy": "Buefy",
    "quasar": "Quasar",
    "primevue": "PrimeVue",
    "primefaces": "PrimeFaces",
    "richfaces": "RichFaces",
    "icefaces": "ICEfaces",
    "omnifaces": "OmniFaces",
    "jsf": "JSF",
    "phpmyadmin": "phpMyAdmin",
    "adminer": "Adminer",
    "cpanel": "cPanel",
    "plesk": "Plesk",
    "webmin": "Webmin",
    "directadmin": "DirectAdmin",
    "vesta": "Vesta",
    "ajax": "AJAX",
    "json": "JSON API",
    "xml": "XML API",
    "graphql": "GraphQL",
    "soap": "SOAP",
    "rest": "REST API",
    "grpc": "gRPC",
    "protobuf": "Protocol Buffers",
    "thrift": "Thrift",
    "avro": "Avro",
    "msgpack": "MessagePack",
    "yaml": "YAML",
    "toml": "TOML",
    "ini": "INI",
    "properties": "Java Properties",
    "env": "Environment Config",
    "dockerfile": "Dockerfile",
    "makefile": "Makefile",
    "cmake": "CMake",
    "autoconf": "Autoconf",
    "automake": "Automake",
    "libtool": "Libtool",
    "maven": "Maven",
    "gradle": "Gradle",
    "ant": "Ant",
    "sbt": "SBT",
    "lein": "Leiningen",
    "mix": "Mix",
    "rebar": "Rebar",
    "cargo": "Cargo",
    "go.mod": "Go Modules",
    "package.json": "Node.js",
    "composer.json": "PHP Composer",
    "requirements.txt": "Python pip",
    "pipfile": "Pipenv",
    "poetry.lock": "Poetry",
    "gemfile": "RubyGems",
    "cargo.toml": "Cargo",
    "pom.xml": "Maven",
    "build.gradle": "Gradle",
    "setup.py": "Python setuptools",
    "pyproject.toml": "Python pyproject",
    "manifest.json": "Web App Manifest",
    "service-worker.js": "Service Worker",
    "sw.js": "Service Worker",
    "web.config": "IIS",
    ".htaccess": "Apache",
    "nginx.conf": "Nginx",
    "httpd.conf": "Apache",
    "apache2.conf": "Apache",
    "lighttpd.conf": "Lighttpd",
    "haproxy.cfg": "HAProxy",
    "traefik.toml": "Traefik",
    "caddyfile": "Caddy",
    "docker-compose.yml": "Docker Compose",
    "docker-compose.yaml": "Docker Compose",
    "kubernetes.yml": "Kubernetes",
    "k8s.yml": "Kubernetes",
    "helm": "Helm",
    "terraform": "Terraform",
    "cloudformation": "CloudFormation",
    "serverless": "Serverless",
    "vercel.json": "Vercel",
    "netlify.toml": "Netlify",
    "firebase.json": "Firebase",
    "app.yaml": "Google App Engine",
    "app.yml": "Google App Engine",
    "elasticbeanstalk": "Elastic Beanstalk",
    "ecs": "ECS",
    "lambda": "Lambda",
    "azure-pipelines": "Azure Pipelines",
    ".gitlab-ci.yml": "GitLab CI",
    "bitbucket-pipelines.yml": "Bitbucket Pipelines",
    "circleci": "CircleCI",
    "github/workflows": "GitHub Actions",
    "jenkinsfile": "Jenkins",
    "gitignore": "Git",
    "gitattributes": "Git",
    "gitmodules": "Git",
    "editorconfig": "EditorConfig",
    "prettierrc": "Prettier",
    "eslintrc": "ESLint",
    "tsconfig": "TypeScript",
    "jsconfig": "JavaScript",
    "babel.config": "Babel",
    "postcss.config": "PostCSS",
    "tailwind.config": "Tailwind",
    "webpack.config": "Webpack",
    "rollup.config": "Rollup",
    "vite.config": "Vite",
    "nuxt.config": "Nuxt",
    "next.config": "Next.js",
    "gatsby-config": "Gatsby",
    "vue.config": "Vue",
    "angular.json": "Angular",
    "tslint.json": "TSLint",
    "pylintrc": "Pylint",
    ".flake8": "Flake8",
    ".pylintrc": "Pylint",
    "mypy.ini": "Mypy",
    ".mypy.ini": "Mypy",
    "pyrightconfig.json": "Pyright",
    "settings.json": "VS Code",
    ".vscode": "VS Code",
    ".idea": "IntelliJ",
    "project": "IDE",
    "workspace": "IDE",
    "nbproject": "NetBeans",
    "eclipse": "Eclipse",
    "netbeans": "NetBeans",
    "androidstudio": "Android Studio",
    "xcode": "Xcode",
    "visualstudio": "Visual Studio",
    "vscode": "VS Code",
    "sublime-project": "Sublime",
    "sublime-workspace": "Sublime",
    "atom": "Atom",
    "vim": "Vim",
    "emacs": "Emacs",
    "nano": "Nano",
    "notepad++": "Notepad++",
    "textmate": "TextMate",
    "bbedit": "BBEdit",
    "ultraedit": "UltraEdit",
    "notepad": "Notepad",
    "wordpad": "WordPad",
    "gedit": "gedit",
    "kate": "Kate",
    "geany": "Geany",
    "mousepad": "Mousepad",
    "xfce": "XFCE",
    "gnome": "GNOME",
    "kde": "KDE",
    "cinnamon": "Cinnamon",
    "mate": "MATE",
    "lxde": "LXDE",
    "lxqt": "LXQt",
    "unity": "Unity",
    "budgie": "Budgie",
    "pantheon": "Pantheon",
    "deepin": "Deepin",
    "enlightenment": "Enlightenment",
    "fluxbox": "Fluxbox",
    "openbox": "Openbox",
    "i3": "i3",
    "sway": "Sway",
    "wayland": "Wayland",
    "x11": "X11",
    "xorg": "Xorg",
    "wayfire": "Wayfire",
    "weston": "Weston",
    "mir": "Mir",
    "gnome-shell": "GNOME Shell",
    "kwin": "KWin",
    "mutter": "Mutter",
    "xfwm4": "Xfwm4",
    "marco": "Marco",
    "metacity": "Metacity",
    "compiz": "Compiz",
    "dwm": "dwm",
    "awesome": "Awesome",
    "qtile": "Qtile",
    "herbstluftwm": "herbstluftwm",
    "bspwm": "bspwm",
}
