"""Static fingerprint signature tables for TechFingerprinter.

Pure data - no logic lives here. Extracted from titan/core/fingerprint.py
so the detection methods stay readable and the tables stay auditable.
"""

from __future__ import annotations

URL_SIGNATURES: dict[str, str] = {
    "graphql": "GraphQL",
    "api/v1": "REST API v1",
    "api/v2": "REST API v2",
    "api/v3": "REST API v3",
    "rest": "REST API",
    "swagger": "Swagger",
    "openapi": "OpenAPI",
    "raml": "RAML",
    "wsdl": "SOAP/WSDL",
    "soap": "SOAP",
    "grpc": "gRPC",
    "jsonrpc": "JSON-RPC",
    "xmlrpc": "XML-RPC",
    "webdav": "WebDAV",
    "caldav": "CalDAV",
    "carddav": "CardDAV",
    "sftp": "SFTP",
    "ftp": "FTP",
    "ssh": "SSH",
    "telnet": "Telnet",
    "rdp": "RDP",
    "vnc": "VNC",
    "smb": "SMB",
    "nfs": "NFS",
    "ldap": "LDAP",
    "kerberos": "Kerberos",
    "radius": "RADIUS",
    "tacacs": "TACACS+",
    "diameter": "Diameter",
    "sip": "SIP",
    "rtp": "RTP",
    "rtsp": "RTSP",
    "rtmp": "RTMP",
    "hls": "HLS",
    "dash": "DASH",
    "m3u8": "HLS",
    "mpd": "DASH",
    "webrtc": "WebRTC",
    "websocket": "WebSocket",
    "sse": "Server-Sent Events",
    "longpolling": "Long Polling",
    "comet": "Comet",
    "ajax": "AJAX",
    "jsonp": "JSONP",
    "cors": "CORS",
    "csrf": "CSRF",
    "xss": "XSS",
    "sqli": "SQLi",
    "rce": "RCE",
    "lfi": "LFI",
    "rfi": "RFI",
    "ssrf": "SSRF",
    "xxe": "XXE",
    "ssti": "SSTI",
    "deserialization": "Deserialization",
    "injection": "Injection",
    "traversal": "Path Traversal",
    "redirect": "Open Redirect",
    "idor": "IDOR",
    "privilege": "Privilege Escalation",
    "authentication": "Authentication",
    "authorization": "Authorization",
    "session": "Session Management",
    "crypto": "Cryptography",
    "ssl": "SSL/TLS",
    "tls": "TLS",
    "certificate": "Certificate",
    "jwt": "JWT",
    "oauth": "OAuth",
    "openid": "OpenID",
    "saml": "SAML",
    "sso": "SSO",
    "mfa": "MFA",
    "2fa": "2FA",
    "totp": "TOTP",
    "hotp": "HOTP",
    "webauthn": "WebAuthn",
    "fido2": "FIDO2",
    "password": "Password",  # pragma: allowlist secret — fingerprint vocabulary
    "passkey": "Passkey",
    "credential": "Credential",  # pragma: allowlist secret — fingerprint vocabulary, not a credential
    "secret": "Secret",  # pragma: allowlist secret — fingerprint vocabulary
    "api_key": "API Key",  # pragma: allowlist secret — fingerprint vocabulary
    "token": "Token",
    "cookie": "Cookie",
    "session_id": "Session ID",
    "csrf_token": "CSRF Token",
    "nonce": "Nonce",
    "salt": "Salt",
    "hash": "Hash",
    "encryption": "Encryption",
    "decryption": "Decryption",
    "signature": "Signature",
    "hmac": "HMAC",
    "rsa": "RSA",
    "ecdsa": "ECDSA",
    "ed25519": "Ed25519",
    "aes": "AES",
    "des": "DES",
    "3des": "3DES",
    "blowfish": "Blowfish",
    "camellia": "Camellia",
    "cast": "CAST",
    "idea": "IDEA",
    "rc4": "RC4",
    "rc5": "RC5",
    "rc6": "RC6",
    "serpent": "Serpent",
    "twofish": "Twofish",
    "threefish": "Threefish",
    "skein": "Skein",
    "keccak": "Keccak",
    "sha": "SHA",
    "md5": "MD5",
    "ripemd": "RIPEMD",
    "whirlpool": "Whirlpool",
    "tiger": "Tiger",
    "gost": "GOST",
    "streebog": "Streebog",
    "blake2": "BLAKE2",
    "blake3": "BLAKE3",
    "argon2": "Argon2",
    "bcrypt": "bcrypt",
    "scrypt": "scrypt",
    "pbkdf2": "PBKDF2",
    "pkcs": "PKCS",
    "x509": "X.509",
    "pem": "PEM",
    "der": "DER",
    "pfx": "PFX",
    "p12": "P12",
    "p7b": "P7B",
    "p7c": "P7C",
    "p10": "P10",
    "csr": "CSR",
    "ca": "CA",
    "ocsp": "OCSP",
    "crl": "CRL",
    "https": "HTTPS",
    "ftps": "FTPS",
    "telnets": "TelnetS",
    "imaps": "IMAPS",
    "pop3s": "POP3S",
    "smtps": "SMTPS",
    "ldaps": "LDAPS",
    "vpns": "VPNs",
    "ipsec": "IPsec",
    "ike": "IKE",
    "ah": "AH",
    "esp": "ESP",
    "tcp": "TCP",
    "udp": "UDP",
    "icmp": "ICMP",
    "ip": "IP",
    "ipv4": "IPv4",
    "ipv6": "IPv6",
    "http": "HTTP",
    "http2": "HTTP/2",
    "http3": "HTTP/3",
    "quic": "QUIC",
    "dns": "DNS",
    "dhcp": "DHCP",
    "ntp": "NTP",
    "snmp": "SNMP",
    "syslog": "Syslog",
    "log": "Logging",
    "monitoring": "Monitoring",
    "metrics": "Metrics",
    "tracing": "Tracing",
    "logging": "Logging",
    "audit": "Audit",
    "security": "Security",
    "waf": "WAF",
    "firewall": "Firewall",
    "ids": "IDS",
    "ips": "IPS",
    "siem": "SIEM",
    "edr": "EDR",
    "xdr": "XDR",
    "mdr": "MDR",
    "soar": "SOAR",
    "dlp": "DLP",
}
