"""Zero-footprint fingerprinting for target reconnaissance."""

from __future__ import annotations

import asyncio
import json
import re
from typing import Any, Dict, List, Optional


class TechFingerprinter:
    def __init__(self):
        self.fingerprint: Dict[str, Any] = {
            "technologies": [],
            "frameworks": [],
            "languages": [],
            "servers": [],
            "headers": {},
            "cookies": [],
            "js_libraries": [],
            "api_types": [],
            "waf": None,
            "cdn": None,
            "language": None,
            "powered_by": None,
            "x_powered_by": None,
            "server": None,
            "x_generator": None,
            "x_drupal": None,
            "x_joomla": None,
            "x_wordpress": None,
            "x_aspnet": None,
            "x_aspnetmvc": None,
            "x_aspnetcore": None,
            "x_phalcon": None,
            "x_laravel": None,
            "x_symfony": None,
            "x_express": None,
            "x_nextjs": None,
            "x_nuxtjs": None,
            "x_svelte": None,
            "x_gatsby": None,
            "x_hugo": None,
            "x_jekyll": None,
            "x_hexo": None,
            "x_gridsome": None,
            "x_eleventy": None,
            "x_11ty": None,
            "x_astro": None,
            "x_sapper": None,
            "x_meteor": None,
            "x_ember": None,
            "x_backbone": None,
            "x_angular": None,
            "x_react": None,
            "x_vue": None,
            "x_preact": None,
            "x_riot": None,
            "x_aurelia": None,
            "x_polymer": None,
            "x_knockout": None,
            "x_mithril": None,
            "x_dojo": None,
            "x_extjs": None,
            "x_sencha": None,
            "x_dojox": None,
            "x_yui": None,
            "x_scriptaculous": None,
            "x_prototype": None,
            "x_mootools": None,
            "x_swfobject": None,
            "x_flash": None,
            "x_silverlight": None,
            "x_java": None,
            "x_asp": None,
            "x_php": None,
            "x_python": None,
            "x_ruby": None,
            "x_perl": None,
            "x_nodejs": None,
            "x_go": None,
            "x_rust": None,
            "x_elixir": None,
            "x_clojure": None,
            "x_scala": None,
            "x_kotlin": None,
            "x_swift": None,
            "x_dart": None,
            "x_typescript": None,
            "x_coffeescript": None,
            "x_livescript": None,
            "x_babel": None,
            "x_webpack": None,
            "x_rollup": None,
            "x_parcel": None,
            "x_vite": None,
            "x_esbuild": None,
            "x_snowpack": None,
            "x_skypack": None,
            "x_jspm": None,
            "x_requirejs": None,
            "x_almond": None,
            "x_curljs": None,
            "x_lodash": None,
            "x_underscore": None,
            "x_ramda": None,
            "x_lazy": None,
            "x_ramda": None,
            "x_immutable": None,
            "x_moment": None,
            "x_date_fns": None,
            "x_dayjs": None,
            "x_luxon": None,
            "x_timeago": None,
            "x_numeral": None,
            "x_accounting": None,
            "x_currency": None,
            "x_money": None,
            "x_bignumber": None,
            "x_decimal": None,
            "x_mathjs": None,
            "x_nerdamer": None,
            "x_math": None,
            "x_statistics": None,
            "x_simple_statistics": None,
            "x_d3": None,
            "x_chartjs": None,
            "x_highcharts": None,
            "x_echarts": None,
            "x_plotly": None,
            "x_vega": None,
            "x_threejs": None,
            "x_phaser": None,
            "x_matterjs": None,
            "x_pixi": None,
            "x_createjs": None,
            "x_howler": None,
            "x_soundjs": None,
            "x_videojs": None,
            "x_plyr": None,
            "x_jwplayer": None,
            "x_flowplayer": None,
            "x_kaltura": None,
            "x_brightcove": None,
            "x_vimeo": None,
            "x_youtube": None,
            "x_facebook": None,
            "x_twitter": None,
            "x_instagram": None,
            "x_tiktok": None,
            "x_linkedin": None,
            "x_pinterest": None,
            "x_reddit": None,
            "x_whatsapp": None,
            "x_telegram": None,
            "x_slack": None,
            "x_discord": None,
            "x_teams": None,
            "x_zoom": None,
            "x_webex": None,
            "x_skype": None,
            "x_google": None,
            "x_aws": None,
            "x_azure": None,
            "x_gcp": None,
            "x_cloudflare": None,
            "x_fastly": None,
            "x_akamai": None,
            "x_vercel": None,
            "x_netlify": None,
            "x_heroku": None,
            "x_render": None,
            "x_fly": None,
            "x_digitalocean": None,
            "x_linode": None,
            "x_vultr": None,
            "x_ovh": None,
            "x_hetzner": None,
            "x_aws_lambda": None,
            "x_azure_functions": None,
            "x_gcp_functions": None,
            "x_cloudflare_workers": None,
            "x_vercel_functions": None,
            "x_netlify_functions": None,
            "x_heroku_functions": None,
            "x_render_functions": None,
            "x_fly_functions": None,
            "x_docker": None,
            "x_kubernetes": None,
            "x_helm": None,
            "x_istio": None,
            "x_nginx": None,
            "x_apache": None,
            "x_lighttpd": None,
            "x_haproxy": None,
            "x_traefik": None,
            "x_caddy": None,
            "x_openssh": None,
            "x_openssl": None,
            "x_gnutls": None,
            "x_nss": None,
            "x_boringssl": None,
            "x_libressl": None,
            "x_openssl": None,
        }

    # PUSH-TO-100 B2 — strong, grounded markers checked BEFORE the generic
    # keyword table. These are real framework signatures (SPA manifests,
    # framework globals, distinctive attributes), not English words — so a
    # page can never inherit a framework from a substring coincidence.
    STRONG_BODY_MARKERS = [
        (r"ng-version=", "Angular"),              # Angular attribute
        (r"<app-root", "Angular"),                # Angular shell element
        (r"_nghost-", "Angular"),                 # Angular host binding
        (r"data-reactroot", "React"),             # React 16+ mount marker
        (r"_reactRootContainer", "React"),        # React 15 mount marker
        (r"__NEXT_DATA__", "Next.js"),            # Next.js data blob
        (r"/_next/static/", "Next.js"),           # Next.js asset path
        (r"__NUXT__", "Nuxt.js"),                 # Nuxt.js data blob
        (r"data-v-[0-9a-f]{6,}", "Vue"),          # Vue scoped-style attr
        (r"__VUE_DEVTOOLS_GLOBAL_HOOK__", "Vue"),
        (r"__SAPPER__", "Sapper"),
        (r"__sveltekit", "SvelteKit"),
        (r"__gatsby", "Gatsby"),
        (r"window\.__remixContext", "Remix"),
        (r"window\.__astro_", "Astro"),
        (r"svelte\.[a-z]+\.js", "Svelte"),
        (r"ember\.(min\.)?js", "Ember"),
        (r"backbone\.(min\.)?js", "Backbone"),
        (r"jquery[.-][0-9]+", "jQuery"),
        (r"wp-content/", "WordPress"),
        (r"drupalSettings", "Drupal"),
        (r"Joomla!", "Joomla"),
        (r"Django\s*[0-9.]*\s*\)?", "Django"),  # Django version banner
        (r"{{ csrf_token }}", "Django"),
        (r"__django__", "Django"),
        (r"laravel_session", "Laravel"),
        (r"csrfmiddlewaretoken", "Django"),
    ]

    # Words too generic to fingerprint anything from a body: they appear in
    # ordinary English prose and in every framework's docs/meta, so even a
    # WORD-BOUNDARY match is not evidence ("play" on a video site, "rest"
    # in "rest of the page", "spring" as a season, "express" as a courier,
    # "react" in marketing copy, "vue"/"slim"/"spark"/"unity" in product
    # names). The unlisted table words ARE allowed to match — word-boundary
    # matching already prevents the "display" -> "play" substring class, and
    # distinctive words ("django", "wordpress", "drupal", "php", "json")
    # are genuine signals when they stand alone. Only the STRONG markers may
    # claim the denied frameworks.
    GENERIC_BODY_WORDS = {
        "play", "rest", "express", "vue", "react", "spring", "slim",
        "spark", "unity", "foundation", "project", "workspace", "status",
    }

    async def analyze(self, response_headers: Dict[str, str], body: str, url: str) -> Dict[str, Any]:
        self.fingerprint["headers"] = {k.lower(): v for k, v in response_headers.items()}
        # B2 — reset accumulated lists so repeated analyze() calls can't grow
        # stale/duplicate entries (a fingerprinter instance is reused across
        # scans in the engine).
        for key in ("technologies", "frameworks", "languages", "servers",
                    "js_libraries", "api_types"):
            self.fingerprint[key] = []
        self._detect_headers()
        self._detect_cookies(response_headers)
        self._detect_body(body)
        self._detect_url(url)
        # B2 — dedupe while preserving order (headers + body + url can name the
        # same technology several times; the scorecard must read clean).
        for key in ("technologies", "frameworks", "languages", "servers",
                    "js_libraries", "api_types"):
            self.fingerprint[key] = list(dict.fromkeys(self.fingerprint[key]))
        return self.fingerprint

    def _detect_headers(self):
        headers = self.fingerprint["headers"]
        header_map = {
            "x-powered-by": "x_powered_by",
            "server": "server",
            "x-generator": "x_generator",
            "x-drupal": "x_drupal",
            "x-joomla": "x_joomla",
            "x-wordpress": "x_wordpress",
            "x-aspnet": "x_aspnet",
            "x-aspnetmvc": "x_aspnetmvc",
            "x-aspnetcore": "x_aspnetcore",
            "x-phalcon": "x_phalcon",
            "x-laravel": "x_laravel",
            "x-symfony": "x_symfony",
            "x-express": "x_express",
            "x-nextjs": "x_nextjs",
            "x-nuxtjs": "x_nuxtjs",
            "x-svelte": "x_svelte",
            "x-gatsby": "x_gatsby",
            "x-hugo": "x_hugo",
            "x-jekyll": "x_jekyll",
            "x-hexo": "x_hexo",
            "x-gridsome": "x_gridsome",
            "x-eleventy": "x_eleventy",
            "x-11ty": "x_11ty",
            "x-astro": "x_astro",
            "x-sapper": "x_sapper",
            "x-meteor": "x_meteor",
            "x-ember": "x_ember",
            "x-backbone": "x_backbone",
            "x-angular": "x_angular",
            "x-react": "x_react",
            "x-vue": "x_vue",
            "x-preact": "x_preact",
            "x-riot": "x_riot",
            "x-aurelia": "x_aurelia",
            "x-polymer": "x_polymer",
            "x-knockout": "x_knockout",
            "x-mithril": "x_mithril",
            "x-dojo": "x_dojo",
            "x-extjs": "x_extjs",
            "x-sencha": "x_sencha",
            "x-dojo": "x_dojo",
            "x-yui": "x_yui",
            "x-scriptaculous": "x_scriptaculous",
            "x-prototype": "x_prototype",
            "x-mootools": "x_mootools",
            "x-swfobject": "x_swfobject",
            "x-flash": "x_flash",
            "x-silverlight": "x_silverlight",
            "x-java": "x_java",
            "x-asp": "x_asp",
            "x-php": "x_php",
            "x-python": "x_python",
            "x-ruby": "x_ruby",
            "x-perl": "x_perl",
            "x-nodejs": "x_nodejs",
            "x-go": "x_go",
            "x-rust": "x_rust",
            "x-elixir": "x_elixir",
            "x-clojure": "x_clojure",
            "x-scala": "x_scala",
            "x-kotlin": "x_kotlin",
            "x-swift": "x_swift",
            "x-dart": "x_dart",
            "x-typescript": "x_typescript",
            "x-coffeescript": "x_coffeescript",
            "x-livescript": "x_livescript",
            "x-babel": "x_babel",
            "x-webpack": "x_webpack",
            "x-rollup": "x_rollup",
            "x-parcel": "x_parcel",
            "x-vite": "x_vite",
            "x-esbuild": "x_esbuild",
            "x-snowpack": "x_snowpack",
            "x-skypack": "x_skypack",
            "x-jspm": "x_jspm",
            "x-requirejs": "x_requirejs",
            "x-almond": "x_almond",
            "x-curljs": "x_curljs",
            "x-lodash": "x_lodash",
            "x-underscore": "x_underscore",
            "x-ramda": "x_ramda",
            "x-lazy": "x_lazy",
            "x-immutable": "x_immutable",
            "x-moment": "x_moment",
            "x-date-fns": "x_date_fns",
            "x-dayjs": "x_dayjs",
            "x-luxon": "x_luxon",
            "x-timeago": "x_timeago",
            "x-numeral": "x_numeral",
            "x-accounting": "x_accounting",
            "x-currency": "x_currency",
            "x-money": "x_money",
            "x-bignumber": "x_bignumber",
            "x-decimal": "x_decimal",
            "x-mathjs": "x_mathjs",
            "x-nerdamer": "x_nerdamer",
            "x-math": "x_math",
            "x-statistics": "x_statistics",
            "x-simple-statistics": "x_simple_statistics",
            "x-d3": "x_d3",
            "x-chartjs": "x_chartjs",
            "x-highcharts": "x_highcharts",
            "x-echarts": "x_echarts",
            "x-plotly": "x_plotly",
            "x-vega": "x_vega",
            "x-threejs": "x_threejs",
            "x-phaser": "x_phaser",
            "x-matterjs": "x_matterjs",
            "x-pixi": "x_pixi",
            "x-createjs": "x_createjs",
            "x-howler": "x_howler",
            "x-soundjs": "x_soundjs",
            "x-videojs": "x_videojs",
            "x-plyr": "x_plyr",
            "x-jwplayer": "x_jwplayer",
            "x-flowplayer": "x_flowplayer",
            "x-kaltura": "x_kaltura",
            "x-brightcove": "x_brightcove",
            "x-vimeo": "x_vimeo",
            "x-youtube": "x_youtube",
            "x-facebook": "x_facebook",
            "x-twitter": "x_twitter",
            "x-instagram": "x_instagram",
            "x-tiktok": "x_tiktok",
            "x-linkedin": "x_linkedin",
            "x-pinterest": "x_pinterest",
            "x-reddit": "x_reddit",
            "x-whatsapp": "x_whatsapp",
            "x-telegram": "x_telegram",
            "x-slack": "x_slack",
            "x-discord": "x_discord",
            "x-teams": "x_teams",
            "x-zoom": "x_zoom",
            "x-webex": "x_webex",
            "x-skype": "x_skype",
            "x-google": "x_google",
            "x-aws": "x_aws",
            "x-azure": "x_azure",
            "x-gcp": "x_gcp",
            "x-cloudflare": "x_cloudflare",
            "x-fastly": "x_fastly",
            "x-akamai": "x_akamai",
            "x-vercel": "x_vercel",
            "x-netlify": "x_netlify",
            "x-heroku": "x_heroku",
            "x-render": "x_render",
            "x-fly": "x_fly",
            "x-digitalocean": "x_digitalocean",
            "x-linode": "x_linode",
            "x-vultr": "x_vultr",
            "x-ovh": "x_ovh",
            "x-hetzner": "x_hetzner",
            "x-aws-lambda": "x_aws_lambda",
            "x-azure-functions": "x_azure_functions",
            "x-gcp-functions": "x_gcp_functions",
            "x-cloudflare-workers": "x_cloudflare_workers",
            "x-vercel-functions": "x_vercel_functions",
            "x-netlify-functions": "x_netlify_functions",
            "x-heroku-functions": "x_heroku_functions",
            "x-render-functions": "x_render_functions",
            "x-fly-functions": "x_fly_functions",
            "x-docker": "x_docker",
            "x-kubernetes": "x_kubernetes",
            "x-helm": "x_helm",
            "x-istio": "x_istio",
            "x-nginx": "x_nginx",
            "x-apache": "x_apache",
            "x-lighttpd": "x_lighttpd",
            "x-haproxy": "x_haproxy",
            "x-traefik": "x_traefik",
            "x-caddy": "x_caddy",
            "x-openssh": "x_openssh",
            "x-openssl": "x_openssl",
            "x-gnutls": "x_gnutls",
            "x-nss": "x_nss",
            "x-boringssl": "x_boringssl",
            "x-libressl": "x_libressl",
        }
        for header, key in header_map.items():
            if header in headers:
                self.fingerprint[key] = headers[header]
                self.fingerprint["technologies"].append(headers[header])

    def _detect_cookies(self, headers: Dict[str, str]):
        cookie_header = headers.get("set-cookie", "")
        if not cookie_header:
            return
        cookies = [c.strip().split("=")[0] for c in cookie_header.split(";") if "=" in c]
        self.fingerprint["cookies"] = cookies
        cookie_indicators = {
            "PHPSESSID": "PHP",
            "JSESSIONID": "Java",
            "ASP.NET_SessionId": "ASP.NET",
            "sessionid": "Django/Flask",
            "laravel_session": "Laravel",
            "ci_session": "CodeIgniter",
            "rack.session": "Ruby/Rack",
            "express.sid": "Express",
            "connect.sid": "Express",
            "_rails_session": "Ruby on Rails",
            "play_session": "Play Framework",
            "sid": "Node.js",
            "csrftoken": "Django",
            "_csrf": "Express/Angular",
            "XSRF-TOKEN": "Laravel",
            "AWSALB": "AWS ALB",
            "AWSALBCORS": "AWS ALB CORS",
            "BIGIPSERVER": "F5 BIG-IP",
            "BIGIP": "F5 BIG-IP",
            "BIGIPSERVER": "F5 BIG-IP",
            "BIGIP": "F5 BIG-IP",
        }
        for cookie_name, tech in cookie_indicators.items():
            if any(cookie_name in c for c in cookies):
                self.fingerprint["technologies"].append(tech)
                self.fingerprint["frameworks"].append(tech)

    def _detect_body(self, body: str):
        body_lower = body.lower()

        # B2 — strong markers first: real framework signatures win even if a
        # generic word also appears (an Angular app that mentions "react" in
        # its copy must stay Angular, not flip to React). Patterns are matched
        # against the lowercased body, so they are lowercased too.
        for pattern, tech in self.STRONG_BODY_MARKERS:
            if re.search(pattern.lower(), body_lower):
                self.fingerprint["technologies"].append(tech)
                self.fingerprint["frameworks"].append(tech)

        tech_indicators = {
            "wordpress": "WordPress",
            "drupal": "Drupal",
            "joomla": "Joomla",
            "laravel": "Laravel",
            "symfony": "Symfony",
            "codeigniter": "CodeIgniter",
            "yii": "Yii",
            "phalcon": "Phalcon",
            "zend": "Zend",
            "cakePHP": "CakePHP",
            "fuelphp": "FuelPHP",
            "kohana": "Kohana",
            "slim": "Slim",
            "silex": "Silex",
            "lumen": "Lumen",
            "spark": "Spark",
            "adonis": "Adonis",
            "hapi": "Hapi",
            "meteor": "Meteor",
            "express": "Express",
            "koa": "Koa",
            "next.js": "Next.js",
            "nuxt.js": "Nuxt.js",
            "svelte": "Svelte",
            "gatsby": "Gatsby",
            "hugo": "Hugo",
            "jekyll": "Jekyll",
            "hexo": "Hexo",
            "gridsome": "Gridsome",
            "eleventy": "Eleventy",
            "astro": "Astro",
            "rails": "Ruby on Rails",
            "django": "Django",
            "flask": "Flask",
            "fastapi": "FastAPI",
            "spring": "Spring",
            "struts": "Struts",
            "play": "Play Framework",
            "asp.net": "ASP.NET",
            "php": "PHP",
            "node.js": "Node.js",
            "react": "React",
            "vue": "Vue",
            "angular": "Angular",
            "jquery": "jQuery",
            "bootstrap": "Bootstrap",
            "tailwind": "Tailwind",
            "foundation": "Foundation",
            "materialize": "Materialize",
            "bulma": "Bulma",
            "semantic-ui": "Semantic UI",
            "antd": "Ant Design",
            "element-ui": "Element UI",
            "vuetify": "Vuetify",
            "buefy": "Buefy",
            "quasar": "Quasar",
            "primevue": "PrimeVue",
            "primefaces": "PrimeFaces",
            "richfaces": "RichFaces",
            "icefaces": "ICEfaces",
            "omnifaces": "OmniFaces",
            "jsf": "JSF",
            "phpmyadmin": "phpMyAdmin",
            "adminer": "Adminer",
            "cpanel": "cPanel",
            "plesk": "Plesk",
            "webmin": "Webmin",
            "directadmin": "DirectAdmin",
            "vesta": "Vesta",
            "ajax": "AJAX",
            "json": "JSON API",
            "xml": "XML API",
            "graphql": "GraphQL",
            "soap": "SOAP",
            "rest": "REST API",
            "grpc": "gRPC",
            "protobuf": "Protocol Buffers",
            "thrift": "Thrift",
            "avro": "Avro",
            "msgpack": "MessagePack",
            "yaml": "YAML",
            "toml": "TOML",
            "ini": "INI",
            "properties": "Java Properties",
            "env": "Environment Config",
            "dockerfile": "Dockerfile",
            "makefile": "Makefile",
            "cmake": "CMake",
            "autoconf": "Autoconf",
            "automake": "Automake",
            "libtool": "Libtool",
            "maven": "Maven",
            "gradle": "Gradle",
            "ant": "Ant",
            "sbt": "SBT",
            "lein": "Leiningen",
            "mix": "Mix",
            "rebar": "Rebar",
            "cargo": "Cargo",
            "go.mod": "Go Modules",
            "package.json": "Node.js",
            "composer.json": "PHP Composer",
            "requirements.txt": "Python pip",
            "pipfile": "Pipenv",
            "poetry.lock": "Poetry",
            "gemfile": "RubyGems",
            "cargo.toml": "Cargo",
            "pom.xml": "Maven",
            "build.gradle": "Gradle",
            "setup.py": "Python setuptools",
            "pyproject.toml": "Python pyproject",
            "manifest.json": "Web App Manifest",
            "service-worker.js": "Service Worker",
            "sw.js": "Service Worker",
            "web.config": "IIS",
            ".htaccess": "Apache",
            "nginx.conf": "Nginx",
            "httpd.conf": "Apache",
            "apache2.conf": "Apache",
            "lighttpd.conf": "Lighttpd",
            "haproxy.cfg": "HAProxy",
            "traefik.toml": "Traefik",
            "caddyfile": "Caddy",
            "docker-compose.yml": "Docker Compose",
            "docker-compose.yaml": "Docker Compose",
            "kubernetes.yml": "Kubernetes",
            "k8s.yml": "Kubernetes",
            "helm": "Helm",
            "terraform": "Terraform",
            "cloudformation": "CloudFormation",
            "serverless": "Serverless",
            "vercel.json": "Vercel",
            "netlify.toml": "Netlify",
            "firebase.json": "Firebase",
            "app.yaml": "Google App Engine",
            "app.yml": "Google App Engine",
            "elasticbeanstalk": "Elastic Beanstalk",
            "ecs": "ECS",
            "lambda": "Lambda",
            "azure-pipelines": "Azure Pipelines",
            ".gitlab-ci.yml": "GitLab CI",
            "bitbucket-pipelines.yml": "Bitbucket Pipelines",
            "circleci": "CircleCI",
            "github/workflows": "GitHub Actions",
            "jenkinsfile": "Jenkins",
            "gitignore": "Git",
            "gitattributes": "Git",
            "gitmodules": "Git",
            "editorconfig": "EditorConfig",
            "prettierrc": "Prettier",
            "eslintrc": "ESLint",
            "tsconfig": "TypeScript",
            "jsconfig": "JavaScript",
            "babel.config": "Babel",
            "postcss.config": "PostCSS",
            "tailwind.config": "Tailwind",
            "webpack.config": "Webpack",
            "rollup.config": "Rollup",
            "vite.config": "Vite",
            "nuxt.config": "Nuxt",
            "next.config": "Next.js",
            "gatsby-config": "Gatsby",
            "vue.config": "Vue",
            "angular.json": "Angular",
            "tslint.json": "TSLint",
            "pylintrc": "Pylint",
            ".flake8": "Flake8",
            ".pylintrc": "Pylint",
            "mypy.ini": "Mypy",
            ".mypy.ini": "Mypy",
            "pyrightconfig.json": "Pyright",
            "settings.json": "VS Code",
            ".vscode": "VS Code",
            ".idea": "IntelliJ",
            "project": "IDE",
            "workspace": "IDE",
            "nbproject": "NetBeans",
            "eclipse": "Eclipse",
            "netbeans": "NetBeans",
            "androidstudio": "Android Studio",
            "xcode": "Xcode",
            "visualstudio": "Visual Studio",
            "vscode": "VS Code",
            "sublime-project": "Sublime",
            "sublime-workspace": "Sublime",
            "atom": "Atom",
            "vim": "Vim",
            "emacs": "Emacs",
            "nano": "Nano",
            "notepad++": "Notepad++",
            "textmate": "TextMate",
            "bbedit": "BBEdit",
            "ultraedit": "UltraEdit",
            "notepad": "Notepad",
            "wordpad": "WordPad",
            "gedit": "gedit",
            "kate": "Kate",
            "geany": "Geany",
            "mousepad": "Mousepad",
            "xfce": "XFCE",
            "gnome": "GNOME",
            "kde": "KDE",
            "cinnamon": "Cinnamon",
            "mate": "MATE",
            "lxde": "LXDE",
            "lxqt": "LXQt",
            "unity": "Unity",
            "budgie": "Budgie",
            "pantheon": "Pantheon",
            "deepin": "Deepin",
            "enlightenment": "Enlightenment",
            "fluxbox": "Fluxbox",
            "openbox": "Openbox",
            "i3": "i3",
            "sway": "Sway",
            "wayland": "Wayland",
            "x11": "X11",
            "xorg": "Xorg",
            "wayfire": "Wayfire",
            "weston": "Weston",
            "mir": "Mir",
            "cinnamon": "Cinnamon",
            "gnome-shell": "GNOME Shell",
            "kwin": "KWin",
            "mutter": "Mutter",
            "xfwm4": "Xfwm4",
            "marco": "Marco",
            "metacity": "Metacity",
            "compiz": "Compiz",
            "kwin": "KWin",
            "xfwm4": "Xfwm4",
            "marco": "Marco",
            "metacity": "Metacity",
            "compiz": "Compiz",
            "dwm": "dwm",
            "awesome": "Awesome",
            "qtile": "Qtile",
            "herbstluftwm": "herbstluftwm",
            "bspwm": "bspwm",
            "i3": "i3",
            "sway": "Sway",
            "wayland": "Wayland",
            "x11": "X11",
            "xorg": "Xorg",
            "wayfire": "Wayfire",
            "weston": "Weston",
            "mir": "Mir",
        }
        for indicator, tech in tech_indicators.items():
            # B2 — generic English words can never claim a framework from a
            # substring ("display" must not yield "Play Framework"). Only the
            # strong markers above may name those technologies.
            if indicator in self.GENERIC_BODY_WORDS:
                continue
            # B2 — word-boundary matching: "play" only matches standalone
            # "play", never inside "display"/"player"/"deploy". Indicators
            # with a leading/trailing dot (e.g. ".htaccess") fall back to
            # substring containment (word boundaries don't apply to dots).
            if indicator[0].isalnum() and indicator[-1].isalnum():
                if re.search(rf"\b{re.escape(indicator)}\b", body_lower):
                    self.fingerprint["technologies"].append(tech)
                    self.fingerprint["frameworks"].append(tech)
            elif indicator in body_lower:
                self.fingerprint["technologies"].append(tech)
                self.fingerprint["frameworks"].append(tech)

    def _detect_url(self, url: str):
        url_lower = url.lower()
        # B2 — URLs carry the same substring trap as bodies ("rest" inside
        # "restaurant", "log" inside "blog", "test" inside "latest"). Match
        # on word boundaries and never let a generic word claim an API type.
        indicators = {
            "graphql": "GraphQL",
            "api/v1": "REST API v1",
            "api/v2": "REST API v2",
            "api/v3": "REST API v3",
            "rest": "REST API",
            "swagger": "Swagger",
            "openapi": "OpenAPI",
            "raml": "RAML",
            "wsdl": "SOAP/WSDL",
            "soap": "SOAP",
            "grpc": "gRPC",
            "jsonrpc": "JSON-RPC",
            "xmlrpc": "XML-RPC",
            "webdav": "WebDAV",
            "caldav": "CalDAV",
            "carddav": "CardDAV",
            "sftp": "SFTP",
            "ftp": "FTP",
            "ssh": "SSH",
            "telnet": "Telnet",
            "rdp": "RDP",
            "vnc": "VNC",
            "smb": "SMB",
            "nfs": "NFS",
            "ldap": "LDAP",
            "kerberos": "Kerberos",
            "radius": "RADIUS",
            "tacacs": "TACACS+",
            "diameter": "Diameter",
            "sip": "SIP",
            "rtp": "RTP",
            "rtsp": "RTSP",
            "rtmp": "RTMP",
            "hls": "HLS",
            "dash": "DASH",
            "m3u8": "HLS",
            "mpd": "DASH",
            "webrtc": "WebRTC",
            "websocket": "WebSocket",
            "sse": "Server-Sent Events",
            "longpolling": "Long Polling",
            "comet": "Comet",
            "ajax": "AJAX",
            "jsonp": "JSONP",
            "cors": "CORS",
            "csrf": "CSRF",
            "xss": "XSS",
            "sqli": "SQLi",
            "rce": "RCE",
            "lfi": "LFI",
            "rfi": "RFI",
            "ssrf": "SSRF",
            "xxe": "XXE",
            "ssti": "SSTI",
            "deserialization": "Deserialization",
            "injection": "Injection",
            "traversal": "Path Traversal",
            "redirect": "Open Redirect",
            "idor": "IDOR",
            "privilege": "Privilege Escalation",
            "authentication": "Authentication",
            "authorization": "Authorization",
            "session": "Session Management",
            "crypto": "Cryptography",
            "ssl": "SSL/TLS",
            "tls": "TLS",
            "certificate": "Certificate",
            "jwt": "JWT",
            "oauth": "OAuth",
            "openid": "OpenID",
            "saml": "SAML",
            "ldap": "LDAP",
            "kerberos": "Kerberos",
            "radius": "RADIUS",
            "tacacs": "TACACS+",
            "diameter": "Diameter",
            "sso": "SSO",
            "mfa": "MFA",
            "2fa": "2FA",
            "totp": "TOTP",
            "hotp": "HOTP",
            "webauthn": "WebAuthn",
            "fido2": "FIDO2",
            "password": "Password",
            "passkey": "Passkey",
            "credential": "Credential",
            "secret": "Secret",
            "api_key": "API Key",
            "token": "Token",
            "cookie": "Cookie",
            "session_id": "Session ID",
            "csrf_token": "CSRF Token",
            "nonce": "Nonce",
            "salt": "Salt",
            "hash": "Hash",
            "encryption": "Encryption",
            "decryption": "Decryption",
            "signature": "Signature",
            "hmac": "HMAC",
            "rsa": "RSA",
            "ecdsa": "ECDSA",
            "ed25519": "Ed25519",
            "aes": "AES",
            "des": "DES",
            "3des": "3DES",
            "blowfish": "Blowfish",
            "camellia": "Camellia",
            "cast": "CAST",
            "idea": "IDEA",
            "rc4": "RC4",
            "rc5": "RC5",
            "rc6": "RC6",
            "serpent": "Serpent",
            "twofish": "Twofish",
            "threefish": "Threefish",
            "skein": "Skein",
            "keccak": "Keccak",
            "sha": "SHA",
            "md5": "MD5",
            "ripemd": "RIPEMD",
            "whirlpool": "Whirlpool",
            "tiger": "Tiger",
            "gost": "GOST",
            "streebog": "Streebog",
            "blake2": "BLAKE2",
            "blake3": "BLAKE3",
            "argon2": "Argon2",
            "bcrypt": "bcrypt",
            "scrypt": "scrypt",
            "pbkdf2": "PBKDF2",
            "pkcs": "PKCS",
            "x509": "X.509",
            "pem": "PEM",
            "der": "DER",
            "pfx": "PFX",
            "p12": "P12",
            "p7b": "P7B",
            "p7c": "P7C",
            "p10": "P10",
            "csr": "CSR",
            "ca": "CA",
            "ocsp": "OCSP",
            "crl": "CRL",
            "tls": "TLS",
            "ssl": "SSL",
            "https": "HTTPS",
            "ssh": "SSH",
            "ftps": "FTPS",
            "sftp": "SFTP",
            "telnets": "TelnetS",
            "imaps": "IMAPS",
            "pop3s": "POP3S",
            "smtps": "SMTPS",
            "ldaps": "LDAPS",
            "vpns": "VPNs",
            "ipsec": "IPsec",
            "ike": "IKE",
            "ah": "AH",
            "esp": "ESP",
            "tcp": "TCP",
            "udp": "UDP",
            "icmp": "ICMP",
            "ip": "IP",
            "ipv4": "IPv4",
            "ipv6": "IPv6",
            "http": "HTTP",
            "http2": "HTTP/2",
            "http3": "HTTP/3",
            "quic": "QUIC",
            "dns": "DNS",
            "dhcp": "DHCP",
            "ntp": "NTP",
            "snmp": "SNMP",
            "syslog": "Syslog",
            "log": "Logging",
            "monitoring": "Monitoring",
            "metrics": "Metrics",
            "tracing": "Tracing",
            "logging": "Logging",
            "audit": "Audit",
            "security": "Security",
            "waf": "WAF",
            "firewall": "Firewall",
            "ids": "IDS",
            "ips": "IPS",
            "siem": "SIEM",
            "edr": "EDR",
            "xdr": "XDR",
            "mdr": "MDR",
            "soar": "SOAR",
            "dlp": "DLP",
            "edr": "EDR",
            "xdr": "XDR",
            "mdr": "MDR",
            "soar": "SOAR",
            "dlp": "DLP",
            "dlp": "DLP",
            "dlp": "DLP",
        }
        for indicator, tech in indicators.items():
            if indicator in self.GENERIC_BODY_WORDS:
                continue
            hit = False
            if indicator[0].isalnum() and indicator[-1].isalnum():
                hit = re.search(rf"\b{re.escape(indicator)}\b", url_lower) is not None
            else:
                hit = indicator in url_lower
            if hit:
                self.fingerprint["technologies"].append(tech)
                self.fingerprint["api_types"].append(tech)
