"""pyproject.toml is the single source of truth; requirements.txt is its lock.

There used to be a hand-maintained ``requirements.in`` listing the same
dependencies a second time, with a comment asking humans to keep the two in
sync. That duplication was the defect: two files could disagree, and only the
``.in`` file was compiled into the lockfile the smoke job installs from.

Now ``requirements.txt`` is resolved straight from ``pyproject.toml``
(``[project].dependencies`` plus the ``full`` and ``dev`` extras), compiled on
a Python 3.10 interpreter — the project's declared floor — so the conditional
dependencies for older interpreters are resolved rather than silently dropped.
There is nothing left to drift. These tests hold that property in place, and additionally
pin the one thing reviewers and scoring tools read off the lockfile: which
entries are *direct* dependencies, expressed as a
``# via titan-scanner (pyproject.toml)`` annotation.
"""

import re
from pathlib import Path

import pytest
import tomllib

ROOT = Path(__file__).resolve().parents[1]

PROJECT_ANCHOR = "titan-scanner"


def _normalize(name: str) -> str:
    """PEP 503 name normalisation, so PyJWT == pyjwt."""
    return re.sub(r"[-_.]+", "-", name).strip().lower()


def _name_of_requirement(line: str) -> str:
    line = line.split("#", 1)[0].strip()
    if not line or line.startswith("-"):
        return ""
    return _normalize(re.split(r"[\s<>=!~\[;]", line, maxsplit=1)[0])


def _pyproject_groups() -> dict[str, set[str]]:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    project = data["project"]
    groups: dict[str, set[str]] = {}
    for section, names in (
        ("runtime", project.get("dependencies", [])),
        *[(f"optional:{group}", deps) for group, deps in project.get("optional-dependencies", {}).items()],
    ):
        groups[section] = {_name_of_requirement(d) for d in names}
    return groups


def _lock_entries() -> dict[str, list[str]]:
    """Map each locked package to the comments attached to its entry.

    A pip/uv lockfile entry looks like::

        aiohttp==3.14.3
            # via titan-scanner (pyproject.toml)

    so the comments following a requirement line say where it came from.
    """
    text = (ROOT / "requirements.txt").read_text(encoding="utf-8")
    entries: dict[str, list[str]] = {}
    current: str | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip():
            continue
        if line.lstrip().startswith("#"):
            if current is not None:
                comment = line.strip().lstrip("#").strip()
                if comment:
                    entries[current].append(comment)
            continue
        name = _name_of_requirement(line)
        if not name:
            continue
        current = name
        entries.setdefault(current, [])
    return entries


def _locked_names() -> set[str]:
    return set(_lock_entries())


def _directly_declared_names() -> set[str]:
    """Packages the lockfile attributes to this project, not to a dependency."""
    return {
        name for name, comments in _lock_entries().items() if any(PROJECT_ANCHOR in comment for comment in comments)
    }


@pytest.mark.parametrize("group", sorted(_pyproject_groups()))
def test_every_pyproject_dependency_is_locked(group):
    declared = _pyproject_groups()[group]
    locked = _locked_names()
    missing = sorted(declared - locked)
    assert not missing, (
        f"{group} dependencies missing from requirements.txt: {missing}. "
        "Regenerate it from pyproject.toml, or they will never reach the "
        "lockfile the smoke job installs from."
    )


@pytest.mark.parametrize("group", sorted(_pyproject_groups()))
def test_every_pyproject_dependency_is_marked_direct(group):
    """Declared dependencies must not read as transitive-only in the lock.

    A dependency declared in pyproject.toml but attributed solely to another
    package reads as zero direct dependencies to anything parsing the lock.
    """
    declared = _pyproject_groups()[group]
    direct = _directly_declared_names()
    unmarked = sorted(declared - direct)
    assert not unmarked, (
        f"{group} dependencies are not annotated as direct in "
        f"requirements.txt: {unmarked}. Regenerate the lock with "
        "`pip-compile --extra full --extra dev "
        "--output-file=requirements.txt pyproject.toml`."
    )


def test_requirements_txt_is_generated_not_hand_edited():
    header = (ROOT / "requirements.txt").read_text(encoding="utf-8")[:200]
    assert "autogenerated by pip-compile" in header, (
        "requirements.txt is the compiled lockfile; regenerate it from pyproject.toml rather than editing it directly."
    )
