"""pyproject.toml and requirements.in must not drift apart.

requirements.in states the rule itself: "Keep this file in sync with
pyproject.toml's dependency lists." Nothing enforced it, and requirements.txt
is compiled from requirements.in — so a dependency added only to pyproject
would never reach the lockfile the smoke job installs from.
"""
import re
import tomllib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]


def _normalize(name: str) -> str:
    """PEP 503 name normalisation, so PyJWT == pyjwt."""
    return re.sub(r"[-_.]+", "-", name).strip().lower()


def _name_of_requirement(line: str) -> str:
    line = line.split("#", 1)[0].strip()
    if not line or line.startswith("-"):
        return ""
    return _normalize(re.split(r"[\s<>=!~\[;]", line, maxsplit=1)[0])


def _pyproject_groups() -> dict[str, set[str]]:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    project = data["project"]
    groups: dict[str, set[str]] = {}
    for section, names in (
        ("runtime", project.get("dependencies", [])),
        *[
            (f"optional:{group}", deps)
            for group, deps in project.get("optional-dependencies", {}).items()
        ],
    ):
        groups[section] = {_name_of_requirement(d) for d in names}
    return groups


def _requirements_in_names() -> set[str]:
    text = (ROOT / "requirements.in").read_text(encoding="utf-8")
    return {n for n in (_name_of_requirement(ln) for ln in text.splitlines()) if n}


@pytest.mark.parametrize("group", sorted(_pyproject_groups()))
def test_every_pyproject_dependency_is_in_requirements_in(group):
    declared = _pyproject_groups()[group]
    pinned_source = _requirements_in_names()
    missing = sorted(declared - pinned_source)
    assert not missing, (
        f"{group} dependencies missing from requirements.in: {missing}. "
        "Add them there and re-run pip-compile, or they will never be locked."
    )


def test_requirements_txt_is_generated_not_hand_edited():
    header = (ROOT / "requirements.txt").read_text(encoding="utf-8")[:200]
    assert "autogenerated by pip-compile" in header, (
        "requirements.txt is the compiled lockfile; regenerate it with "
        "pip-compile rather than editing it directly."
    )
