"""Tests for titan.core.waf — WAF detection and payload re-encoding."""

from titan.core.waf import (
    WAFTracker, WAFInfo, reencode_payload, get_bypass_variants,
    _url_encode, _double_encode, _unicode_encode, _sql_comment_inject,
    _case_variation,
)


class TestWAFDetection:
    """WAFTracker.detect() flags WAF blocking responses."""

    def test_cloudflare_detected(self):
        """Cloudflare challenge page → WAF detected."""
        t = WAFTracker()
        body = "<title>Attention Required! | Cloudflare</title>"
        info = t.detect("https://example.com/admin", 403, body, {"CF-Ray": "abc123"})
        assert info is not None
        assert info.waf_name == "cloudflare"
        assert info.confidence > 0.8

    def test_modsecurity_detected(self):
        """ModSecurity block page → WAF detected."""
        t = WAFTracker()
        body = "This error was generated by Mod_Security"
        info = t.detect("https://example.com/api", 403, body, {})
        assert info is not None
        assert info.waf_name == "modsecurity"

    def test_aws_waf_detected(self):
        """AWS WAF headers → WAF detected."""
        t = WAFTracker()
        info = t.detect("https://example.com/", 403, "", {"x-amzn-waf-action": "block"})
        assert info is not None
        assert info.waf_name == "aws_waf"

    def test_akamai_detected(self):
        """Akamai block page → WAF detected."""
        t = WAFTracker()
        body = "Reference #18.abc123"
        info = t.detect("https://example.com/", 403, body, {"Server": "AkamaiGHost"})
        assert info is not None
        assert info.waf_name == "akamai"

    def test_generic_denied_detected(self):
        """Generic 'Access Denied' → generic WAF with lower confidence."""
        t = WAFTracker()
        info = t.detect("https://example.com/", 403, "Access Denied", {})
        assert info is not None
        assert info.waf_name == "generic_waf"
        assert info.confidence < 0.8

    def test_no_waf_on_200(self):
        """200 OK → no WAF detected."""
        t = WAFTracker()
        info = t.detect("https://example.com/", 200, "OK", {})
        assert info is None

    def test_no_waf_on_404(self):
        """404 → no WAF detected."""
        t = WAFTracker()
        info = t.detect("https://example.com/nope", 404, "Not Found", {})
        assert info is None

    def test_no_waf_on_401(self):
        """401 → not checked for WAF (it's an auth issue, not a WAF issue)."""
        t = WAFTracker()
        info = t.detect("https://example.com/auth", 401, "Unauthorized", {})
        assert info is None

    def test_waf_cached(self):
        """Second call for same URL returns cached result."""
        t = WAFTracker()
        body = "Cloudflare WAF block"
        info1 = t.detect("https://example.com/admin", 403, body, {"CF-Ray": "x"})
        info2 = t.detect("https://example.com/admin", 403, "different body", {})
        assert info1 is info2  # same object (cached)

    def test_is_waf_blocked(self):
        """is_waf_blocked returns True after detection."""
        t = WAFTracker()
        assert not t.is_waf_blocked("https://example.com/admin")
        t.detect("https://example.com/admin", 403, "Cloudflare block", {"CF-Ray": "x"})
        assert t.is_waf_blocked("https://example.com/admin")

    def test_different_routes_independent(self):
        """WAF on route A doesn't affect route B."""
        t = WAFTracker()
        t.detect("https://example.com/admin", 403, "Cloudflare block", {"CF-Ray": "x"})
        assert t.is_waf_blocked("https://example.com/admin")
        assert not t.is_waf_blocked("https://example.com/public")


class TestPayloadReencoding:
    """Re-encoding strategies produce valid bypass variants."""

    def test_url_encode_special_chars(self):
        """URL encoding converts <, >, ', etc. to %XX."""
        encoded = _url_encode("SELECT * FROM users WHERE id=1' OR '1'='1")
        assert "<" not in encoded or "%3C" in encoded
        assert "'" not in encoded or "%27" in encoded

    def test_double_encode(self):
        """Double encoding converts % to %25."""
        single = _url_encode("SELECT * FROM users WHERE id=1' OR '1'='1")
        double = _double_encode("SELECT * FROM users WHERE id=1' OR '1'='1")
        assert "%25" in double

    def test_unicode_encode_sql_keywords(self):
        """Unicode encoding breaks SQL keywords."""
        result = _unicode_encode("SELECT * FROM users")
        assert result != "SELECT * FROM users"  # keywords changed

    def test_case_variation(self):
        """Case variation changes letter case."""
        import random
        random.seed(42)  # deterministic for testing
        result = _case_variation("SELECT")
        assert result != "SELECT"  # at least some letters changed

    def test_sql_comment_inject(self):
        """SQL comment injection breaks keywords."""
        result = _sql_comment_inject("SELECT * FROM users")
        assert "/**/" in result
        assert "SEL/**/ECT" in result

    def test_auto_encode(self):
        """Auto strategy produces a different payload."""
        result = reencode_payload("SELECT * FROM users", "auto")
        assert isinstance(result, str)
        assert len(result) > 0

    def test_bypass_variants_count(self):
        """get_bypass_variants returns 0-6 variants."""
        variants = get_bypass_variants("SELECT * FROM users WHERE id=1' OR '1'='1")
        assert 0 <= len(variants) <= 6
        # All variants should be different from original
        for v in variants:
            assert v != "SELECT * FROM users WHERE id=1' OR '1'='1"

    def test_bypass_variants_for_path_traversal(self):
        """Path traversal payloads get null byte variant."""
        variants = get_bypass_variants("../../../etc/passwd")
        # Should have at least URL-encoded and null-byte variants
        assert len(variants) >= 1

    def test_bypass_variants_for_sql_injection(self):
        """SQL injection payloads get comment-inject variant."""
        variants = get_bypass_variants("1' UNION SELECT password FROM users--")
        # Should have comment-inject variant
        has_comment = any("/**/" in v for v in variants)
        assert has_comment

    def test_null_payload_unchanged(self):
        """Empty or simple payloads produce no variants."""
        variants = get_bypass_variants("hello")
        # "hello" has no injection chars, so few/no variants
        assert len(variants) <= 2

    def test_reencode_preserves_structure(self):
        """Re-encoded payloads preserve the general structure."""
        original = "1' OR '1'='1"
        url_encoded = reencode_payload(original, "url")
        # Should still contain the logical operators (just encoded)
        assert "OR" in url_encoded or "4F" in url_encoded.upper()


class TestWAFIntegration:
    """WAF tracker works with the engine."""

    def test_engine_has_waf_tracker(self):
        """TitanEngine initializes a WAFTracker."""
        import yaml, os
        os.chdir(os.path.join(os.path.dirname(__file__), '..'))
        from titan.core.engine import TitanEngine
        with open("config.yaml") as f:
            config = yaml.safe_load(f)
        e = TitanEngine(config)
        assert hasattr(e, "_waf_tracker")
        assert isinstance(e._waf_tracker, WAFTracker)

    def test_waf_info_dataclass(self):
        """WAFInfo has expected fields."""
        info = WAFInfo(waf_name="cloudflare", confidence=0.9, blocked_status=403)
        assert info.waf_name == "cloudflare"
        assert info.confidence == 0.9
        assert info.blocked_status == 403
