"""PUSH-TO-100 Phase C — scorecard rendering + persistence.

The public backing: a markdown table anyone can check, plus scorecard.json
for the dashboard. Aggregation is pure; file writes are atomic (tmp+rename,
same pattern as the site index).
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Dict, List

from bench.benchmark import summarize


def render_table(rows: List[Dict[str, Any]]) -> str:
    """Pure: render challenge rows as a markdown table."""
    lines = [
        "| Challenge | Endpoint | Attack type | Outcome | Evidence |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r.get('name', '')} | `{r.get('endpoint', '')}` | "
            f"{r.get('attack_type', '')} | **{r.get('outcome', '')}** | "
            f"`{r.get('evidence', '')}` |"
        )
    return "\n".join(lines)


def render_scorecard(benchmark: Dict[str, Any]) -> str:
    """Pure: full markdown scorecard for one benchmark run."""
    s = benchmark.get("summary", {})
    lines = [
        f"# Benchmark — {benchmark.get('target', '')}",
        "",
        f"- **Scanned** {benchmark.get('scanned_at', 'n/a')} · "
        f"{benchmark.get('scan_seconds', 0)}s",
        f"- **Pass rate** {s.get('pass_rate', 0)}% · "
        f"{s.get('hits', 0)}/{s.get('reachable', 0)} reachable challenges captured",
        f"- **Hits** {s.get('hits', 0)} · **Suspicious** {s.get('suspicious', 0)} · "
        f"**Misses** {s.get('misses', 0)} · **N/A** {s.get('na', 0)}",
        "",
    ]
    if benchmark.get("scan_error"):
        lines += [f"> Scan error: {benchmark['scan_error']}", ""]
    lines += [render_table(benchmark.get("rows", [])), ""]
    lines += [
        "*Methodology: each challenge is a known-vulnerable endpoint; HIT = the"
        " expected attack type was reported verified for that endpoint. N/A ="
        " the endpoint was never reached (checkpoint/driver/error), never a"
        " false MISS. Generated by the PUSH-TO-100 benchmark rig.*",
        "",
    ]
    return "\n".join(lines)


def write_scorecard(benchmark: Dict[str, Any], out_dir: str = "bench/results") -> Path:
    """Persist scorecard.md + scorecard.json atomically. Returns the dir."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "scorecard.md").write_text(
        render_scorecard(benchmark), encoding="utf-8"
    )
    tmp = out / "scorecard.json.tmp"
    tmp.write_text(json.dumps(benchmark, indent=2), encoding="utf-8")
    tmp.replace(out / "scorecard.json")
    return out


def merge_runs(previous: Dict[str, Any], new: Dict[str, Any]) -> Dict[str, Any]:
    """Pure: merge a new run into the accumulated scorecard history (best
    outcome per challenge, keyed by challenge id)."""
    merged_rows: Dict[str, Dict[str, Any]] = {}
    for r in previous.get("rows", []):
        merged_rows[r.get("id", "")] = r
    for r in new.get("rows", []):
        cid = r.get("id", "")
        prev = merged_rows.get(cid)
        order = {"hit": 3, "suspicious": 2, "miss": 1, "na": 0}
        if not prev or order.get(r.get("outcome", "na"), 0) > order.get(prev.get("outcome", "na"), 0):
            merged_rows[cid] = r
    return {
        "target": new.get("target", previous.get("target", "")),
        "last_scan": new.get("scanned_at", time.strftime("%Y-%m-%dT%H:%M:%S")),
        "scanned_at": new.get("scanned_at", time.strftime("%Y-%m-%dT%H:%M:%S")),
        "runs": previous.get("runs", 0) + 1,
        "rows": sorted(merged_rows.values(), key=lambda r: r.get("id", "")),
        "summary": summarize(list(merged_rows.values())),
    }
